### ISSUE TITLE
[Proposal] New functionality. Compare dependencies between two builds.

### ISSUE THREAD

**Issue by sboishtyan** [autonomousapps/dependency-analysis-android-gradle-plugin#189]
I'm always frustrated when I update or add some new dependency and my build fails

Regular path to fix:
- Made builds with `--scan` before and after dependency changes
- Try to parse by eyes `dependencies` or `dependencyInsight` task outputs
 And that path has a lot of pain and repetitive actions

I want to make a tool which:
- will dump dependencies in readable and parseable format, maybe JSON
- will compare two dumps and print verdict: what dependencies new, what dependencies changed the version, and what dependencies removed
I consider your plugin has a part which able to make dependencies tree representation. And I want to reuse that part.

If you are interested I see a few options:
- Add functionality to the current plugin 
- Add functionality to new plugin with reusing of your dependency representation
- You could give me advice on how I could create that plugin with simple copy-paste from your sources
- You already knew something like the plugin I want
- You have no time to discuss my idea

Thank you for your attention.

**Comment by autonomousapps** [comment]
Thank you for the proposal.

Have you considered gradle dependency locking? https://docs.gradle.org/current/userguide/dependency_locking.html

**Comment by sboishtyan** [comment]
> Have you considered Gradle dependency locking?
I've used it first-time today. 
I used it in two ways:
- made a lockfile 
- add dependency
- made assemble
- got hard-readable output, but better than anything else
 and
- made a lockfile
- commit it
- write a new lockfile
- compare difference with git
- this way easier

I don't like
- flatness of lockfile
- hard-readable console output

Do you know about the behaviour in situations:
- What Will happen If someone creates a new module without `--write-locks`
- Will Gradle print conflicts in all modules or fail on first?

**Comment by autonomousapps** [comment]
Unfortunately, I don't have much experience with that feature. I referenced it because I thought it might meet your needs. You can always ask questions like that in the gradle community slack.

I don't think this is a feature I want to add to this plugin, as it feels like significant scope creep. However, I'm happy to provide you advice on how to achieve this. If all you care about is the actual dependencies, both declared and transitive, I don't think it will be too hard to write a plugin that traverses the graph and prints the data in json format.
