### ISSUE TITLE
Redundant transitive dependencies report

### ISSUE THREAD

**Issue by stephanenicolas** [autonomousapps/dependency-analysis-android-gradle-plugin#210]
In 0.50.0, I have this report generated:

```
Unused dependencies which should be removed:
- api(deps.workflow.legacy.rx2)

Transitively used dependencies that should be declared directly as indicated:
- api(deps.okio)
- api(deps.workflow.legacy.core)
- api(deps.workflow.core)
- api(deps.kotlin.stdlib_jdk6_do_not_use)
- implementation(deps.okio) // duplicate
- implementation(deps.workflow.legacy.core) // duplicate
- implementation(deps.workflow.core) // duplicate
- implementation(deps.kotlin.stdlib_jdk6_do_not_use) // duplicate
```

**Comment by autonomousapps** [comment]
I've discovered this only impacts `AdvicePrinterTask`, which is why it went under the radar. `AdviceSubprojectAggregationTask`, which is what _now_ prints to the console, doesn't have this behavior.

It's still worth addressing, but we should talk about how best to move forward to support your use-case with the recent changes to the plugin.
