### ISSUE TITLE
`buildHealth` execution on CI environment leads to GC overhead OutMemoryError

### ISSUE THREAD

**Issue by sboishtyan** [autonomousapps/dependency-analysis-android-gradle-plugin#216]
plugin=0.50
branch=https://github.com/avito-tech/avito-android/tree/dependencies-analysis-0.50
gradle=6.5
agp=3.6.2
buildscan=https://scans.gradle.com/s/qbe2q7cuabqhc

**Describe the bug**
When I execute `buildHealth` locally everything works fine. But every CI execution leads to OutOfMemoryError
On CI build is executed in Docker.
shell_script=https://github.com/avito-tech/avito-android/blob/dependencies-analysis-0.50/build.sh
Everything was going bad at line ` ./gradlew -p subprojects build ${GRADLE_ARGS};` where $GRADLE_ARGS are simple Gradle properties 

**To Reproduce**
Because it didn't reproduce at my local machine I tried to collect more info about GC by adding flags to JVM
`org.gradle.jvmargs=-Xmx2g -XX:+HeapDumpOnOutOfMemoryError -XX:+PrintGCDetails -XX:HeapDumpPath=./outputs/dumps -XX:+UseGCOverheadLimit -XX:GCTimeLimit=10 -Dfile.encoding=UTF-8` 
I saw effect only for `-XX:GCTimeLimit=10 ` before adding that flag I've been waiting for 25 minutes while GC killing my build. Now it's only 8 minutes

**Expected behavior**
` ./gradlew -p subprojects build ${GRADLE_ARGS};` finishes with success

**Additional context**
I add a file with logs. But I think they are useless. Maybe you have any idea how to collect more data for investigation?
[github.com_avito-android_Github_PullRequest_checks_1625.log](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/files/4848043/github.com_avito-android_Github_PullRequest_checks_1625.log)

**Comment by autonomousapps** [comment]
I think you probably just need to give your CI worker more memory, and/or set the value of `-Xmx` to something higher, like 4g.

That said, if you create a memory profile of the plugin in action and send it my way, I'd be happy to take a look and see if there are obvious hotspots where I could improve performance. You can use gradle-profiler to help with that.
GitHub <notifications@github.com> wrote:
“plugin=0.50
 branch=https://github.com/avito-tech/avito-android/tree/dependencies-analysis-0.50
 gradle=6.5
 agp=3.6.2
 buildscan=https://scans.gradle.com/s/qbe2q7cuabqhc

Describe the bug
 When I execute buildHealth locally everything works fine. But every CI execution leads to OutOfMemoryError
 On CI build is executed in Docker.
 shell_script=https://github.com/avito-tech/avito-android/blob/dependencies-analysis-0.50/build.sh
 Everything was going bad at line  ./gradlew -p subprojects build ${GRADLE_ARGS}; where $GRADLE_ARGS are simple Gradle properties

To Reproduce
 Because it didn't reproduce at my local machine I tried to collect more info about GC by adding flags to JVM
 org.gradle.jvmargs=-Xmx2g -XX:+HeapDumpOnOutOfMemoryError -XX:+PrintGCDetails -XX:HeapDumpPath=./outputs/dumps -XX:+UseGCOverheadLimit -XX:GCTimeLimit=10 -Dfile.encoding=UTF-8
 I saw effect only for -XX:GCTimeLimit=10 before adding that flag I've been waiting for 25 minutes while GC killing my build. Now it's only 8 minutes

Expected behavior
  ./gradlew -p subprojects build ${GRADLE_ARGS}; finishes with success

Additional context
 I add a file with logs. But I think they are useless. Maybe you have any idea how to collect more data for investigation?
github.com_avito-android_Github_PullRequest_checks_1625.log”

**Comment by sboishtyan** [comment]
Ok, I try to increase heap size and then will profile.
Only because locally everything is fine stops me from the increasing heap size

**Comment by autonomousapps** [comment]
Your CI workers are probably doing more things then you do locally. It's not uncommon, in my experience, for CI to require a larger heap than local builds.
GitHub <notifications@github.com> wrote:
“Ok, I try to increase heap size and then will profile.
 Only because locally everything is fine stops me from the increasing heap size”

**Comment by sboishtyan** [comment]
Could you help me with gradle-profiler setup. What profiler should I use? What additional properties should I add to my benchmark scenario?

**Comment by autonomousapps** [comment]
I really need to write a blog post on using gradle-profiler.

First you want to clone and install gradle-profiler: https://github.com/gradle/gradle-profiler. Then, you'll want to use it with AsyncProfiler (which I _think_ gradle-profiler will install for you if you don't already have it). Now profile your build
```
gradle-profiler --profile async-profiler --async-profiler-event alloc --project-dir <root-dir-of-build> buildHealth
```

**Comment by sboishtyan** [comment]
I finally did all info described in [gist ](https://gist.github.com/sboishtyan/114e59b59d04eec53610e77979262143)

**Comment by autonomousapps** [comment]
Thanks. I will take a look when I get a chance.

**Comment by autonomousapps** [comment]
Taking a look at the flamechart you shared, the three areas with the greatest memory usage are (in order of priority):
1. `DependencyReportTask` -> `ArtifactToComponentTransformer.analyzeJar` -> `ByteStreamsKt.readBytes` & `ClassReader.accept`
2. `ConstantUsageDetectionWorkAction` -> `JvmDetector.find` -> ... -> `JvmConstantMemberFinder.find`
3. `InlineMemberExtractionWorkAction` -> `InlineDependenciesFinder.find`  -> ... -> `InlineMemberFinder.find`

**Comment by sboishtyan** [comment]
Does it look expectable for you?

**Comment by autonomousapps** [comment]
I'm not at all surprised to see those are the biggest users of memory. I'm not sure I'll be able to do anything about it, but I will take a look. 
GitHub <notifications@github.com> wrote:
“Does it look expectable for you?”

**Comment by autonomousapps** [comment]
I'm going to leave some notes in this comment, editing as I learn more.

For the first item, `ArtifactToComponentTransformer.analyzeJar()` already uses a caching strategy to prevent re-analyzing the same jar more than once. It's a bit naive and jars _may_ be analyzed more than once, but the count will _not_ greatly exceed 1.

**Comment by autonomousapps** [comment]
I strongly suspect that I can completely collapse the duplicate analysis between 1 and 2, which would cut about ~16% of memory usage in the build you sent me the profile for. So I'll give that a try and let's see what happens!

**Comment by sboishtyan** [comment]
I consider that it's a classic trade-off between speed and memory usage
You cache everything but you don't know if you will reuse it in the future because of that memory usage looks like a spike but speed is the best.

I see only one way to optimize memory usage with less speed impact.
You could make the first iteration to build full dependencies graph and then delete cache entries as soon as you meet all coincidences of dependency when you make real analyzation.

**Comment by autonomousapps** [comment]
I had a bit of inspiration today and found a way to cut out one of the analysis passes, which should -- based on your profile -- cut ~16% of the allocations. It should also use the CPU slightly less.

**Comment by sboishtyan** [comment]
Cool, I will take a look and check. Should I check before the release with that fix or we simply could wait for the release?

**Comment by autonomousapps** [comment]
You can check the snapshot once I merge to `main`, which will be soon. Instructions at https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/wiki/Adding-to-your-project.

I will release this with 0.54, no eta at this time.

**Comment by sboishtyan** [comment]
I see GC behaves differently now. Max amount of memory didn't change but in execution with other tasks it will use memory more efficient
<img width="419" alt="Screenshot 2020-07-22 at 22 44 38" src="https://user-images.githubusercontent.com/8560287/88221945-e1cc8500-cc6d-11ea-9431-b3cd04baaa0e.png">

**Comment by autonomousapps** [comment]
Thank you for the feedback. Nice to see some data.
