### ISSUE TITLE
Incompatibility with Spring Boot plugin ?

### ISSUE THREAD

**Issue by vincent-fuchs** [autonomousapps/dependency-analysis-android-gradle-plugin#219]
**Plugin version**
0.52.0

**Gradle version**
6.5

**Describe the bug**
in a Spring Boot (2.3.1) project, using Spring Boot plugin, I get below error when running the task : 

> * What went wrong:
> Could not evaluate onlyIf predicate for task ':bootstrap:abiAnalysisMain'.
> The jar task (named 'jar') has been disabled. Please enable it.

If I remove `apply plugin: 'org.springframework.boot'` from my gradle file, then the task executes

**Expected behavior**

I would want to execute the plugin on a Spring Boot project

**Comment by autonomousapps** [comment]
The issue is that this plugin _requires_ the jar task as an input to several of its tasks. That exception is a custom one the plugin throws when it detects that the task has been disabled (which seems to be the case with the Spring Boot plugin).

I don't have any experience with Spring Boot, do you know why it disables the jar task?

**Comment by gotson** [comment]
I was gonna raise the same issue.

Spring Boot's gradle plugin disables the `jar` task because it builds a fat jar instead, details here: https://docs.spring.io/spring-boot/docs/current/gradle-plugin/reference/html/#reacting-to-other-plugins-java

This really is a show stopper, Spring Boot is the most used Java framework, not being able to use both is too bad.

I would suggest you take it directly to their repo about this issue and see how it can be solved: https://github.com/spring-projects/spring-boot/tree/master/spring-boot-project/spring-boot-tools/spring-boot-gradle-plugin

**Comment by autonomousapps** [comment]
@gotson thank you for this
> Spring Boot's gradle plugin disables the jar task because it builds a fat jar instead

That's the final bit of context I needed to understand what was going on. 

# Temporary workaround
If you want to try out this plugin right now, simply enable those jar tasks. I may be biased, but I think you might learn some interesting things about your project.

# Long-term
I would like this plugin to be compatible with Spring Boot. The simplest solution is to leverage some prior art and simply analyze class files instead of the final jar. I can't analyze the fat jar because it obviously includes all dependencies and the plugin would report everything as used, since it's all there in the final jar!

**Comment by autonomousapps** [comment]
I have a PR that I believe resolves this issue, but it doesn't quite complete the story for Spring Boot. Given that it produces a fat jar, I suspect I should treat its artifacts like applications rather than a libraries. If so, that implies no meaningful ABI.

Can someone confirm that? Would it ever make sense for a boot application to have an `api` dependency?

**Comment by gotson** [comment]
> Can someone confirm that? Would it ever make sense for a boot application to have an `api` dependency?

Spring Boot produces applications, but you may need to confirm that with @wilkinsona

**Comment by autonomousapps** [comment]
If you're using Spring Boot, do you apply that plugin to all modules in a project? Typically alongside java vs java-library? Or...?

Most of my experience is in Android development, so I'm just not familiar with what is standard in Spring Boot land.

**Comment by gotson** [comment]
You still need `java` when you develop in Java (i don't). `java-library` is only recently added to Gradle, and used only when you create a library that will be published on Maven for instance.

You indeed apply the spring boot gradle plugin alongside `java` or `kotlin` plugin.

**Comment by wilkinsona** [comment]
> Spring Boot produces applications, but you may need to confirm that with @wilkinsona

That's correct. While a Spring Boot application may be built from multiple modules, we expect only a single module to have the `org.springframework.boot` plugin applied. This module builds the complete application, typically in the form of a fat jar. There's no need for that module to have any `api` dependencies as it shouldn't be used as a dependency.

**Comment by autonomousapps** [comment]
I have merged the PR that fixes the issue with trying to rely on a jar task that is often disabled. Now we just look at the class files generated by (optionally) javac and (optionally) kotlinc. However, I haven't done anything about the fact that the plugin is now likely to erroneously suggest that spring boot modules have `api` dependencies. I will open a separate issue for that and link it to this issue. Thanks everyone involved for answering my questions about that.

**Comment by autonomousapps** [comment]
The [latest release](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/main/CHANGELOG.md#version-0530) finishes support for Spring Boot. Please let me know if you run into any issues.
