### ISSUE TITLE
Project cannot sync/build when pluggin applied and added doLast to a specific task

### ISSUE THREAD

**Issue by extmkv** [autonomousapps/dependency-analysis-android-gradle-plugin#243]
**Plugin version**
0.55.0

**Gradle version**
6.5.1
Kotlin:       1.3.72
Groovy:       2.5.11
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          13 (Oracle Corporation 13+33)
OS:           Mac OS X 10.14.6 x86_64

**Android Gradle Plugin (AGP) version**
4.0.1

**Describe the bug**
This is not the main issues but when I apply the plugin the plugin tasks didn't appear under the tasks tab on android studio, but if I run the `.gradlew` tasks I can see them there:

```
❯ ./gradlew tasks
...
Dependency-analysis tasks
-------------------------
abiAnalysisMain - Produces a report of the ABI of this project
abiAnalysisStagingGlobalDebug - Produces a report of the ABI of this project
abiAnalysisStagingGlobalRelease - Produces a report of the ABI of this project
adviceMain - Provides advice on how best to declare the project's dependencies
advicePrinterMain - Displays advice on screen
advicePrinterStagingGlobalDebug - Displays advice on screen
advicePrinterStagingGlobalRelease - Displays advice on screen
adviceReport - Aggregates advice reports across all subprojects
adviceStagingGlobalDebug - Provides advice on how best to declare the project's dependencies
adviceStagingGlobalRelease - Provides advice on how best to declare the project's dependencies
aggregateAdvice - Aggregates advice from a project's variant-specific advice tasks
analyzeClassUsageMain - Produces a report of all classes referenced by a given set of class files
analyzeClassUsageStagingGlobalDebug - Produces a report of all classes referenced by a given jar
analyzeClassUsageStagingGlobalRelease - Produces a report of all classes referenced by a given jar
artifactsReportMain - Produces a report of all classes referenced by a given jar
artifactsReportStagingGlobalDebug - Produces a report of all classes referenced by a given jar
artifactsReportStagingGlobalRelease - Produces a report of all classes referenced by a given jar
buildHealth - Generates holistic advice for whole project
...
```

My main issues starts when I try to add `doLast` to a specific task like the `buildHealth`. 

```
inside root build.gradle
buildHealth.doLast {
    processHealthReport()
}
```

If run the task `./gradlew buildHealth` everything work as aspect, my function `processHealthReport` is called  in the eend and all the data processed, the problem is syncing the project, always fails the sync/build, the output says the `buildHealth` it's an unknown property:

```
A problem occurred evaluating root project 'ProjectName'.
> Could not get unknown property 'buildHealth' for root project 'ProjectName' of type org.gradle.api.Project.
```

I think the problems is related about the tasks not appearing in the android studio, I tried to list tasks inside the `build.gradle` and I cannot see them there.

Already tried:
- Applying the plugin in 2 different ways;
- Create a new task with a `dependsOn buildHealth`
- Downgrade the plugin to other versions;

**Comment by autonomousapps** [comment]
AS fails to sync because we check if the plugin is being configured inside AS (vs from a command line invocation) and if so, disable almost everything. This is due to an issue reported whereby using the **make** button in AS would cause more compilation than necessary; i.e. it was an issue with AS that we tried to workaround in the manner I just described. So in summary, what you've experienced is 100% expected.

I can think of three ways forward:
1. Reconsider disabling the plugin in the face of a weird AS bug
1. Make the disabling optional
1. You change how you do your post-processing.

Regarding that last option, your approach of adding a `doLast {}` to `buildHealth`, while not _wrong_ exactly, is not how the plugin is intended to be used. The [wiki](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/wiki/Post-processing) explains our post-processing support. Please consider giving this a try, and you shouldn't (I think) see this sync issue:
```
A problem occurred evaluating root project 'ProjectName'.
> Could not get unknown property 'buildHealth' for root project 'ProjectName' of type org.gradle.api.Project.
```
you shouldn't see it because you'll no longer be attempting to directly configure `buildHealth`.

**Comment by extmkv** [comment]
Regarding the post-processing, we tried and the extension always fails, cannot find the input file.

Bassicly we decided to create a new task and run one after the other one. `./gradlew buildHealth generateDependyReport`

**Comment by autonomousapps** [comment]
> we tried and the extension always fails, cannot find the input file.

That's very strange. Would you mind sharing your configuration? I have [an automated test](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/main/src/functionalTest/groovy/com/autonomousapps/jvm/PostProcessingSpec.groovy) that verifies that post-processing works.
