### ISSUE TITLE
artifactsReportMain fails with a NoSuchMethodError using okio

### ISSUE THREAD

**Issue by BraisGabin** [autonomousapps/dependency-analysis-android-gradle-plugin#254]
**Build scan link**
https://gradle.com/s/3xgo4alnj6ndk

**Plugin version**
0.56.0 (same happens with 0.55.0)

**Gradle version**
6.4.1

**Describe the bug**
when I run `./gradlew buildHealth` I get this error:

```
Execution failed for task ':artifactsReportMain'.
> okio.BufferedSource.getBuffer()Lokio/Buffer;
```

(full stack trace in the scan)

**To Reproduce**
1. clone https://github.com/BraisGabin/detekt/
2. checkout `dependency-analysis`
3. run `./gradlew buildHealth`

**Expected behavior**
It doesn't crash

**Additional context**
I want to analyse the dependencies of `detekt`.

**Comment by autonomousapps** [comment]
This might be due to your project having a lower version of Okio on the build classpath than the plugin uses. Try bumping to 2.6.0 if possible. You use 1.13.0 / 1.16.0: https://scans.gradle.com/s/3xgo4alnj6ndk/build-dependencies?dependencies=okio&expandAll

To solve this on the plugin side, I would need to bundle and shade the Okio dependency so it doesn't conflict with users. It's something I have on my todo list, but I just haven't gotten around to it.

**Comment by BraisGabin** [comment]
Yeah! It works now :) Now I need to understang why all those `implementation` should be `api` and try to find a way to move them to `implementation` again. Great plugin :)

I think that a talk about this topic would be great. My understanding about `implementation`/`api` was "always use implementation, is faster". But it seems like a more complex topic.
