### ISSUE TITLE
Adding plugin breaks apollographql/apollo-android

### ISSUE THREAD

**Issue by ephemient** [autonomousapps/dependency-analysis-android-gradle-plugin#277]
**Build scan link**
https://scans.gradle.com/s/fzkt45a2vsqfs

**Plugin version**
0.59.0

**Gradle version**
6.6.1

**Android Gradle Plugin (AGP) version**
4.0.1

**Describe the bug**

**To Reproduce**
1. build.gradle.kts
    ```
    plugins {
        id("com.autonomousapps.dependency-analysis") version "0.59.0"
    }
    ```
    lib/build.gradle.kts
    ```
    plugins {
        id("java-library")
        id("com.apollographql.apollo") version "2.3.1"
    }
    apollo {
        service("example") {
            schemaFile.set(file("schema.graphql"))
        }
    }
    ```
    lib/schema.graphql
    ```
    schema {
    }
   ```
    settings.gradle.kts
    ```
    include("lib")
    ```
2. `gradle :lib:generateApolloSources`
3.
    ```
    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':lib:generateMainExampleApolloSources'.
    > Could not initialize class com.apollographql.apollo.compiler.parser.introspection.IntrospectionSchema
    ```

**Expected behavior**
GraphQL task can run
(in this simple example, it'll still fail as it's missing some more graphql setup, but it shouldn't encounter NoClassDefFoundError/NoSuchFieldError)

**Additional context**
It works without com.autonomousapps.dependency-analysis plugin.

**Comment by autonomousapps** [comment]
Thanks for the report. I will take a look.

**Comment by autonomousapps** [comment]
I believe I have discovered the cause of this issue. Apollo is using OkHttp 4.5.0, but my plugin uses 4.7.2. If you google the "companion" error, they're all about OkHttp clashes. If I add this to the root `build.gradle`
```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath "com.squareup.okhttp3:okhttp:4.7.2"
    }
}
```
then the problem goes away (build still fails, of course).

So the simplest solution is to update OkHttp in Apollo. A more robust solution, which I want to do eventually, is create a fat-jar plugin that shades all its dependencies so these kinds of issues can't happen anymore.

**Comment by vlsi** [comment]
Is OkHttp really needed in dependency-analysis-android-gradle-plugin?

**Comment by vlsi** [comment]
The issue is caused by `okio.ByteString`

```
com.autonomousapps:dependency-analysis-gradle-plugin:0.59.0
\--- com.squareup.moshi:moshi:1.9.2
     \--- com.squareup.okio:okio:1.16.0
```

On the other hand, `apollographql` needs `okio:2.8.0`

**Comment by autonomousapps** [comment]
I use OkHttp to promote a staging repo on nexus/sonatype. It's only a buildSrc dependency. Thanks for pointing out that it's actually a transitive dependency of Moshi. Which, yes, I use extensively.

The best workaround now is to bump Okio, then. The only way to prevent these kinds of issues in the future is to create a relocated fatjar, but I haven't had time to deal with the combination of Shadow and Gradle's shit documentation.

**Comment by vlsi** [comment]
> The only way to prevent these kinds of issues in the future is to create a relocated fatjar

I believe you are missing `classloader isolation` in Woker API: https://guides.gradle.org/using-the-worker-api/#changing_the_isolation_mode

It provides isolation without the need to make a shadow jar. That would make the dependencies smaller, it would reduce users caches, and it would avoid shading hassle (which is not that easy due to licensing issues when you bundle third-party code).

**Comment by autonomousapps** [comment]
You're assuming all of the plugin's work is in workers but this unfortunately is not so. Moshi is used in task actions throughout. So worker classloader isolation would not solve this (unless I'm missing something). 
GitHub <notifications@github.com> wrote:
““The only way to prevent these kinds of issues in the future is to create a relocated fatjar”

I believe you are missing classloader isolation in Woker API: https://guides.gradle.org/using-the-worker-api/#changing_the_isolation_mode

It provides isolation without the need to make a shadow jar. That would make the dependencies smaller, it would reduce users caches, and it would avoid shading hassle (which is not that easy due to licensing issues when you bundle third-party code).”

**Comment by vlsi** [comment]
> Moshi is used in task actions throughout

I assume task actions can be run in classloader-isolated Worker actions.
In other words, `@TaskAction` method could submit a work, so Moshi and other dependencies could be loaded there.

I don't think you expose Moshi classes as a public API for your task configuration properties or something like that.

**Comment by autonomousapps** [comment]
Believe me, if I could move the work to a worker action, I would. But some things are not yet serializable, and there is no way to do it.

**Comment by autonomousapps** [comment]
and actually Moshi classes are exposed. See https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/main/src/main/kotlin/com/autonomousapps/internal/utils/moshi.kt. There was some reason I couldn't make them `internal`.

Furthermore, I provide a post-build hook to let users register tasks to automate dependency cleanup, and this uses moshi at runtime to deserialize json data in a file into a data structure in memory.

**Comment by autonomousapps** [comment]
@ephemient have you had a chance to try the workaround I suggested?

**Comment by martinbonnin** [comment]
Hi 👋 , we've had the same kind of issues with `sqldelight` as well, see https://github.com/apollographql/apollo-android/issues/2359. 
I'm not 100% clear on how the various Gradle classloaders work but this is usually solved by declaring all the plugins in a single "central" location so that Gradle can resolved dependencies properly. In this case, you can declare all plugins in the root project without applying them and apply them in individual projects:

build.gradle.kts
```
plugins {
    id("com.autonomousapps.dependency-analysis").version("0.59.0").
    id("com.apollographql.apollo").version("2.31").apply(false)
}
```

lib/build.gradle.kts
```
plugins {
    id("java-library")
    id("com.apollographql.apollo")
}
```
