### ISSUE TITLE
Plugin cannot be applied from external build scripts

### ISSUE THREAD

**Issue by mqueiroz1995** [autonomousapps/dependency-analysis-android-gradle-plugin#283]
**Plugin version**
v0.59.0

**Gradle version**
v6.1.1

**Android Gradle Plugin (AGP) version**
v4.0.1

**Describe the bug**

In  big projects, configuring the whole build in build.gradle can create a big and messy configuration file. 

To prevent that, I'm applying this plugin from an external build script. However, in Gradle, [third-party plugins cannot be applied by ID from external build scripts](https://github.com/gradle/gradle/issues/1262), so I have to apply the plugin by its class instead of its ID.

The problem is that internally, when `autoApply=true`, the plugin is applied to all subprojects automatically using the nonexistent id.

**To Reproduce**

Create external configuration script:

```groovy
// dependency-analysis.gradle
buildscript {
    repositories {
        mavenLocal()
        jcenter()
    }

    dependencies {
        classpath "com.autonomousapps:dependency-analysis-gradle-plugin:0.59.1"
    }
}

apply plugin: com.autonomousapps.DependencyAnalysisPlugin
```

Apply script to root `build.gradle`:

```groovy
apply from: 'dependency-analysis.gradle'
```

Sync project and get error message:
```
Plugin with id 'com.autonomousapps.dependency-analysis' not found.
```

After setting `autoApply` to false and applying to subprojects manyally:

```groovy
buildscript {
    repositories {
        mavenCentral()
    }

    dependencies {
        classpath "com.autonomousapps:dependency-analysis-gradle-plugin:0.59.0"
    }
}

allprojects {
    apply plugin: com.autonomousapps.DependencyAnalysisPlugin
}

dependencyAnalysis {
    autoApply(false)
}
```

Sync project and get another error message:
```
Unable to load class 'org.jetbrains.kotlin.gradle.dsl.KotlinProjectExtension'.
Possible causes for this unexpected error include:
Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
Re-download dependencies and sync project (requires network)

The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
Stop Gradle build processes (requires restart)

Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.

In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.
```

**Expected behavior**

It should be possible to apply the plugin from external build scripts.

**Comment by autonomousapps** [comment]
Thanks for the report. I will take a look.
GitHub <notifications@github.com> wrote:
“Plugin version
 v0.59.0

Gradle version
 v6.1.1

Android Gradle Plugin (AGP) version
 v4.0.1

Describe the bug

In big projects, configuring the whole build in build.gradle can create a big and messy configuration file.

To prevent that, I'm applying this plugin from an external build script. However, in Gradle, third-party plugins cannot be applied by ID from external build scripts, so I have to apply the plugin by its class instead of its ID.

The problem is that internally, when autoApply=true, the plugin is applied to all subprojects automatically using the nonexistent id.

To Reproduce

Create external configuration script:

// dependency-analysis.gradle
buildscript {
    repositories {
        mavenLocal()
        jcenter()
    }

    dependencies {
        classpath "com.autonomousapps:dependency-analysis-gradle-plugin:0.59.1"
    }
}

apply plugin: com.autonomousapps.DependencyAnalysisPluginApply script to root build.gradle:

apply from: 'dependency-analysis.gradle'Sync project and get error message:

Plugin with id 'com.autonomousapps.dependency-analysis' not found.

After setting autoApply to false and applying to subprojects manyally:


buildscript {
    repositories {
        mavenCentral()
    }

    dependencies {
        classpath "com.autonomousapps:dependency-analysis-gradle-plugin:0.59.0"
    }
}

allprojects {
    apply plugin: com.autonomousapps.DependencyAnalysisPlugin
}

dependencyAnalysis {
    autoApply(false)
}Sync project and get another error message:

Unable to load class 'org.jetbrains.kotlin.gradle.dsl.KotlinProjectExtension'.
Possible causes for this unexpected error include:
Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
Re-download dependencies and sync project (requires network)

The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
Stop Gradle build processes (requires restart)

Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.

In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

Expected behavior

It should be possible to apply the plugin from external build scripts.”

**Comment by autonomousapps** [comment]
Another thing you could try is to apply the plugin as a precompiled script plugin. Are you familiar with those? I just resolved an issue that was preventing their use, and it will be available at 0.61.0 (upcoming release).

**Comment by mqueiroz1995** [comment]
Thanks for the quick response.

Not really aware about precompiled script plugins, but will take a look at the docs. Is the code that makes it possible already in the repo?

**Comment by autonomousapps** [comment]
Yes, the code is already available on the `main` branch.

I will update the wiki to discuss how to do this when I release, but it looks like this:
```
// buildSrc/build.gradle.kts
plugins {
  `kotlin-dsl`
}
dependencies {
  implementation("com.autonomousapps:dependency-analysis-gradle-plugin:${latest_version}")
}
```
```
// buildSrc/src/kotlin/root-convention.gradle.kts
plugins {
  id("com.autonomousapps:dependency-analysis")
}
```
```
// root build.gradle[.kts]
plugins {
  id("root-convention")
}
```
Please note this also works if you add the plugin as an included build so you can test the latest, unpublished, code.

**Actually you can write your code in Groovy or Kotlin, but I only have experience (and can write from memory in a GH comment) with the latter.**

**Comment by mqueiroz1995** [comment]
I'm reading a bit about composite builds and precompiled script plugins. Although they are a nice way to overcome some limitations of Kotlin DSL and to isolate build coattentionnfiguration, they add a lot of complexity and I'm not sure if it's worth it in our current project scenario.

It would be really nice if applying the plugin from a helper script worked.

Anyway, thank you very much for the attention, I'll give a shot in my free time, in some personal project.

**Comment by autonomousapps** [comment]
Have you considered applying the plugin directly in the root script, but configuring it from your script plugin?

**Comment by crimsonvspurple** [comment]
I believe I have a same/similar issue.

I'm adding
- `id 'com.autonomousapps.dependency-analysis'` in `buildSrc/src/main/groovy/asdf.root.gradle`
- `dependencies { implementation "com.autonomousapps.dependency-analysis:com.autonomousapps.dependency-analysis.gradle.plugin:1.20.0 }` in `buildSrc/build.gradle`

When I apply `asdf.root` on projects using:
```
plugins {
	id 'asdf.root'
}
```

it throws error saying 
```
An exception occurred applying plugin request [id: 'amplify.lib']
   > Failed to apply plugin 'asdf.root'.
      > Failed to apply plugin 'com.autonomousapps.dependency-analysis'.
         > You must apply the plugin to the root project. Current project is :commons
```

I am able to add two other spring boot plugins in same manner; so not sure why this one is not working. Any help would be appreciated.

**Comment by kelmer44** [comment]
Im having the same issue as @crimsonvspurple here, any suggestions?

**Comment by autonomousapps** [comment]
> You must apply the plugin to the root project. Current project is :commons

The plugin _requires_ that it be applied to the root project, in addition to subprojects.
