### ISSUE TITLE
Adding this plugin makes gradle think that I have an additional gradle project

### ISSUE THREAD

**Issue by ColtonIdle** [autonomousapps/dependency-analysis-android-gradle-plugin#313]
Alright. Buckle up because this one is admittedly weird... and it could be argued that it's not the fault of the `dependency-analysis-android-gradle-plugin`, _but_ I think that maybe this plugin is doing _something_ wrong.

Applying this plugin somehow messes with the gradle configuration of a project so that the root "project" is now considered a project to gradle, and the "root" android app module is no longer seen as a project root.

It's kind of hard to explain, but let me use an example where this came up.

I was playing around with this project https://github.com/tfcporciuncula/readme-graph which is cool because it gives me a nice graph of my gradle modules. The "root" app module is a square, while all of the modules it depends on are connected to it. This looks like this:

![project dot](https://user-images.githubusercontent.com/31751141/97045199-551eb500-1543-11eb-8d79-29d7b70965a8.png)

But if I add the dep analysis gradle plugin to the readme-graph project in the root build.gradle file:
```
buildscript {
  ext.kotlin_version = "1.4.10"

  repositories {
    google()
    jcenter()
  }

  dependencies {
    classpath "com.android.tools.build:gradle:4.0.1"
    classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    classpath "com.autonomousapps:dependency-analysis-gradle-plugin:0.63.0" <==== add this line to the readme-graph repo
  }
}

apply plugin: "com.autonomousapps.dependency-analysis"  <==== add this line to the readme-graph repo

allprojects {
  repositories {
    google()
    jcenter()
  }

  apply from: rootProject.file('gradle/common.gradle')
}

task clean(type: Delete) {
  delete rootProject.buildDir
}

apply from: file('gradle/projectDependencyGraph.gradle')
```

Then I get a graph that looks like this

![project dot](https://user-images.githubusercontent.com/31751141/97045493-d6764780-1543-11eb-8bd0-64da028e3253.png)

This has me convinced that `dependency-analysis-android-gradle-plugin` is doing something funky/weird that it shouldn't be? At first I thought that it was just applying any plugin to a root folder would cause this, but I tried other plugins like 

```
apply plugin: 'org.jlleitschuh.gradle.ktlint'
apply plugin: "com.github.ben-manes.versions"
```

and they did not cause the same issue to my module graph as this plugin did. This is the graph after applying ktlint or ben-manes-version plugin

![project dot](https://user-images.githubusercontent.com/31751141/97045199-551eb500-1543-11eb-8d79-29d7b70965a8.png)

@autonomousapps do you think theres any way around this? It might not seem like a big deal, but maybe theres some underlying issue and this could potentially cause some bad effects while using some other plugins if users aren't expecting their root project to be considered a project to gradle.

If you look at the two images I attached you can see that there are two issues there. 
1 is that my app module is no longer considered the root (no longer a square shape)
2 is that the root ": " node appears in the graph

If you look at the gradle task that generates the graph you can see that this is the code that builds the list of "projects"

```
      project.configurations.all { config ->
        config.dependencies
            .withType(ProjectDependency)
            .collect { it.dependencyProject }
            .each { dependency ->
              projects.add(project)
              projects.add(dependency)
              rootProjects.remove(dependency)

              def graphKey = new Tuple2<Project, Project>(project, dependency)
              def traits = dependencies.computeIfAbsent(graphKey) { new ArrayList<String>() }

              if (config.name.toLowerCase().endsWith('implementation')) {
                traits.add('style=dotted')
              }
            }
      }
```

So the read project only has a `projects` with size 4, but adding this plugin increases the `projects` size to 5, which I do not think is right.

**Comment by autonomousapps** [comment]
There are a couple of things to say about this.

The first is that you have always had a root project. Every gradle build does. The existence of a root `build.gradle` file, next to the `settings.gradle` file, is your indication of this.

I don't know what `readme-graph` does, but from what you're showing me it looks like it looks at project dependencies in order to compute and then display a graph. Without applying this plugin, then the projects only have the "normal" dependencies you might expect for an Android project. In particular, there is no dependency from the root to any other module.

Btw, when I say "dependency" I explicitly mean this:
```groovy
dependencies {
  implementation project(':bla')
}
```

My plugin does indeed add dependencies, on the root, to every other module, using a special configuration. The subprojects all publish artifacts to that configuration so they can be consumed by the root without having to explicitly set inter-project task dependencies, which is a very big no-no in Gradle-land. See for example [this](https://docs.gradle.org/current/userguide/cross_project_publications.html).

So in point of fact this plugin is following current Gradle best practices, and what you're seeing is what I would expect.

You may consider filing an issue against that other project to be more discriminatory in how it walks the project graph. I would guess it's looking at _any_ configuration (which would include my special configuration), where instead it should probably look for a few well-known ones like `implementation`, `api`, `compileOnly`, etc. Or it could provide some customization option to set the root, or a different option to ignore a particular node.

**Comment by ColtonIdle** [comment]
@autonomousapps thanks for taking a look. I found out about this task from this article https://medium.com/google-developer-experts/how-to-display-your-android-project-dependency-graph-in-your-readme-file-e52dcadafa7a but the task itself was made by Jake Wharton.

Kind of sucks that by adding this plugin I get a somewhat "messier" module graph, but I might try to update the task to only look at "well known" configurations... or maybe I can opt out your "special configuration". Does it have a particular name?

**Comment by autonomousapps** [comment]
https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/main/src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt#L40-L41

**Comment by ColtonIdle** [comment]
Woop woop. Thanks! Appreciate the pointers @autonomousapps AND I appreciate the explanation ("The first is that you have always had a root project. Every gradle build does.")

CHEERS
