### ISSUE TITLE
Check dependencies by resources

### ISSUE THREAD

**Issue by Jacks0N23** [autonomousapps/dependency-analysis-android-gradle-plugin#331]
**Build scan link**

**Plugin version**
0.65.0 (on latest version `:module:projectHealth` doesn't work, don't find out  why yet)

**Gradle version**
6.7

**Android Gradle Plugin (AGP) version**
4.1.1

**Describe the bug**
I have special module for fonts only. When connected as a dependency and run `:fonts-module:projectHealth` then plugin tells that I should remove it, which is wrong. And the same behavior with other dependencies by resource like themes, strings & etc

**Expected behavior**
No recommendations to delete this dependency

**Comment by autonomousapps** [comment]
I am almost certain that this is due to a known limitation described [here](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/wiki/Compatibilities-&-Limitations#limitations). If your `gradle.properties` is missing
```
android.namespacedRClass=true
```
then that is the issue.

Since a number of people have already upvoted this, I will explain a bit further. It would actually be impossible to conclusively determine the provenance of a resource when those resources aren't namespaced, thanks to the way that AGP merges resources as it traverses up the dependency graph towards your `app` module. The best we could do is to have a heuristic such that, when seeing something like `R.what.ever`, don't recommend removing any dependency that supplies a `what.ever` resource. And this would be quite complicated to code.

In the meantime, you can [configure the plugin](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/wiki/Customizing-plugin-behavior#failure-conditions-and-filtering) to ignore certain issues. In your specific case, you could add the following to your root `build.gradle`
```groovy
dependencyAnalysis
  issues {
    all {
      onUnusedDependencies {
        exclude(':fonts-module')
      }
    }
  }
}
```
and that module will no longer be reported as "unused."

PS: Regarding "the latest version doesn't work", there was a bug in 0.67.0 that would cause a crash due to an NPE in certain circumstances. That was resolved in 0.68.0 (released yesterday). Please give it a try and, if you still have an issue, please file so I can take a look.

**Comment by Jacks0N23** [comment]
Thank you for fast and detailed response!
Yes, I don't have `android.namespacedRClass=true` in my project because it's very big and I'll need refactor a lot.
I understand problem and use now `exclude `

P.S. 0.68. works fine
but, i still have those null instead of api/implementation some times, do you know why this happening?
![image](https://user-images.githubusercontent.com/9117565/100488060-0ef9da00-311d-11eb-8ec7-caa71bd6b305.png)

**Comment by autonomousapps** [comment]
@Jacks0N23 could you file a new issue with more information?

**Comment by blundell** [comment]
For anyone coming to this late..

`android.namespacedRClass=true`

is now named:

`android.nonTransitiveRClass=true`

**Comment by bartek-wesolowski** [comment]
I think the problem still remains when resources (e.g. drawables or colors) are used only in another module's XML files (e.g. layouts). I have an icon in a library module and when I use it in another module's XML layout, the library module with an icon is indicated as unused. I'm using version 1.0.0-rc02.

**Comment by autonomousapps** [comment]
@bartek-wesolowski do you have a minimal reproducer?

**Comment by bartek-wesolowski** [comment]
It seems that the problem appears when using library resources marked as private. They probably shouldn't be used anyway, so it's not the plugin's fault.

**Comment by autonomousapps** [comment]
Closing. Please re-open if any actionable information makes itself known.
