### ISSUE TITLE
KotlinProjectExtension not present when AGP and Kotlin plugins not in the classpath

### ISSUE THREAD

**Issue by BetweenTwoBits** [autonomousapps/dependency-analysis-android-gradle-plugin#368]
**Build scan link**
https://scans.gradle.com/s/dvelwso2ujfou

**Plugin version**
0.71.0

**Gradle version**
7.0-milestone-1

**Android Gradle Plugin (AGP) version**
4.1.2

**Describe the bug**
When the root `build.gradle.kts` file does not have a buildscript block with android/kotlin plugins on its classpath, trying to run a build with the plugin enabled yields the following error:
```
* What went wrong:
A problem occurred configuring project ':app'.
> Type org.jetbrains.kotlin.gradle.dsl.KotlinProjectExtension not present
```

**To Reproduce**
1. apply the plugin in the root build.gradle.kts file, with no buildscript clock defined. Example repo here: https://github.com/BetweenTwoBits/android-no-buildSrc/tree/version_catalog

**Expected behavior**
Hoping that the plugin can fulfill this dependency on its own so that the AGP and Kotlin plugins don't have to exist on the classpath.

**Comment by autonomousapps** [comment]
@BetweenTwoBits thanks for the issue. This is a longstanding issue that I'd like to resolve, but haven't had time to yet. There are a few workarounds for you, including the one you've already identified. They all reduce to "add the Kotlin plugin to the classpath." You can use `buildscript`, or you could add KGP to `buildSrc`, or you could do this:
```groovy
// root build.gradle
id 'org.jetbrains.kotlin.<jvm|android>' version '<some-version>' apply false
```
note the `apply false` at the end. This adds the plugin to the classpath without actually applying it.

**Comment by autonomousapps** [comment]
@BetweenTwoBits I've had time to investigate this and come to the conclusion -- with some regret -- that this is Working as Intended :tm: There's a good discussion of it on the gradle community slack [here](https://gradle-community.slack.com/archives/CA745PZHN/p1619065317165600).

I don't like any of the alternatives. What I can do is update the wiki with a FAQ section (because this comes up regularly) explaining what's going on.

It's possible we'll get some new facilities sometime this year with Gradle 7 that will help, but no promises.
