### ISSUE TITLE
Jar task no longer run when this plugin is added.

### ISSUE THREAD

**Issue by stealthrabbi** [autonomousapps/dependency-analysis-android-gradle-plugin#380]
When this plugin as added to a gradle file, `gradlew build` no longer calls the `jar` task, so no jars are made in build/libs

**Comment by autonomousapps** [comment]
@stealthrabbi sorry for the delay, I only just now saw this. That is happening probably because of [this line](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/main/src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt#L1000). You can tell the plugin not to do that by setting a system property:
```
./gradlew buildHealth -Ddependency.analysis.clear.artifacts=false
```
or in `gradle.properties`
```
systemProp.dependency.analysis.clear.artifacts=false
```
The reason for the default was to address a common use-case among IDE users, who often click the "make" button, which ended up triggering `buildHealth` because of [how Gradle works](https://github.com/gradle/gradle/issues/10797), and this led to slower than expected IDE builds.
