### ISSUE TITLE
Should advise to change dependencies to runtimeOnly when that makes sense

### ISSUE THREAD

**Issue by lschwahn** [autonomousapps/dependency-analysis-android-gradle-plugin#387]
**Plugin version**
0.72.0

**Gradle version**
6.8.3

**Describe the bug**
We are using this plugin on a big monolith Multi-Project and identified some dependencies that are not used by our code, but not reported as unused by the plugin. The following dependencies are affected:
```
dependencies {
    implementation 'org.apache.cxf:cxf-core:3.1.2'
    implementation 'org.apache.poi:poi-ooxml:3.17'
    implementation 'org.hibernate:hibernate-core:5.2.13.Final'
    implementation 'org.hibernate:hibernate-envers:5.2.13.Final'
    implementation 'org.junit.jupiter:junit-jupiter-engine:5.7.1'
    implementation 'org.junit.vintage:junit-vintage-engine:5.7.1'
    implementation 'org.postgresql:postgresql:42.2.4'
    implementation 'org.springframework.batch:spring-batch-core:4.2.1.RELEASE'
    implementation 'org.springframework:spring-core:5.2.4.RELEASE'
}
```

**To Reproduce**
I created a small sample project to reproduce this issue: 
1. git clone https://github.com/lschwahn/gradle-dep-analysis-unused-dependencies.git
2. ./gradlew buildHealth

```
> Task :buildHealth
Advice for root project
Looking good! No changes needed


BUILD SUCCESSFUL in 2s
26 actionable tasks: 25 executed, 1 up-to-date
```

None of the dependencies are declared as unused.

**Expected behavior**
Every dependency from the list above is reported as unused, as they are not used by the java-code inside the sample project.

**Comment by autonomousapps** [comment]
All of the dependencies you've listed contain [service loaders](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/ServiceLoader.html), except for `org.apache.poi:poi-ooxml`, which contains a [security provider](https://docs.oracle.com/javase/8/docs/api/java/security/Provider.html). These are inherently runtime facilities that are challenging to detect at compile time. For this reason, the advice filters out any "unused" dependency that contains any runtime or otherwise undetectable-at-compile-time facility. You can see the code where this happens [here](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/main/src/main/kotlin/com/autonomousapps/internal/advice/Advisor.kt#L136-L139).

I'm going to close this as works-as-intended. If you have thoughts on how to better communicate this issue, either via the console output or the wiki, I'm open to hearing it.

**Comment by autonomousapps** [comment]
Almost forgot to mention, there is one thing you could do to check this situation in the future. For example:
```
./gradlew reason --id org.apache.poi:poi-ooxml

> Task :lib:reason
You asked about the dependency org.apache.poi:poi-ooxml. There is no advice regarding this dependency.

Shortest path to org.apache.poi:poi-ooxml from the current project:
:lib
\--- org.apache.poi:poi-ooxml

Dependency org.apache.poi:poi-ooxml provides the following:
- 670 classes
- 1187 public constants
- provides these security providers:
  - org.apache.poi.poifs.crypt.dsig.services.RelationshipTransformService$1
Reason DOT: /home/tony/workspace/temp/gradle-dep-analysis-unused-dependencies/lib/build/reports/dependency-analysis/graph-reason.gv
```
This is the [reason](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/wiki/Tasks#reason) feature. It's a work in progress, but as you can see here, it shows that the given dependency provides a security provider.

Unfortunately, I haven't yet added support to show that the other dependencies provide service loaders, so that remains slightly opaque.

**Comment by jjohannes** [comment]
@autonomousapps may I ask if there is a reason why these dependencies do not produce an _advice_ at all? I would expect an _advice_ to move the dependency to "runtimeOnly". (And then I can decide if I move it to `runtimeOnly` or remove it completely.)

E.g., if I have

```
implementation("org.apache.poi:poi-ooxml")
```

I would expect an advice suggesting to move it to `runtimeOnly`.

I think what `report` tells me is sufficient if I use that, but I would also like to have an advice when I do `projectAdvice()` in a post-processing task.

 Or am I missing something?

**Comment by jjohannes** [comment]
I think there is some inconsistency right now. If I have no code at all using the dependency, I get no advice. No matter if it is `implementation` or `api`. (This is where I think I should get `runtimeOnly`.)

But as soon as I start using classes from the dependency, the plugin will tell me if I got `api` vs. `implementation` right (as I would expect).

**Comment by autonomousapps** [comment]
@jjohannes that happens at [this line](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/main/src/main/kotlin/com/autonomousapps/transform/StandardTransform.kt#L132).

For reasons that I honestly can't quite remember right now, the plugin does not currently recommend changing any dependency to `runtimeOnly`. And in your case, because the plugin can tell that the dependency in question has a runtime facility, it also won't recommend _removing_ it as "unused." It basically decides that it is correctly declared and emits no advice.

One thing you can do to verify this is to run `./gradlew :my-module:reason --id org.apache.poi:poi-ooxml`, and I would expect it to tell you that that dependency "implies runtimeOnly" (see [here](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/main/src/main/kotlin/com/autonomousapps/model/intermediates/Reason.kt#L105-L113)).

Given that it's just a single line of code controlling this, changing the behavior would be straightforward, although some tests would certainly fail with that change.

WDYT?

**Comment by jjohannes** [comment]
@autonomousapps thanks for pointing out the code responsible. If you don't mind, I'll give removing that line a try and see if it works as expected in my use case and check which tests are failing. Then we can decide if the change is "ok".

I agree that I won't recommend _removing_. Otherwise the service loader / security provider detection would have no use at all, right? Still I think it is only an indication that something _might_ be needed at runtime (but maybe it is not needed at all). That's why I think an _advice_ that lets the user know that this in **not** needed at compile time (neither _implementation_ nor _api_) is useful. Because that is what we know for sure.

**Comment by autonomousapps** [comment]
Sounds good. Let's give it a try and see what happens. 

On April 19, 2022, GitHub ***@***.***> wrote:
> @autonomousapps <https://github.com/autonomousapps> thanks for
> pointing out the code responsible. If you don't mind, I'll give
> removing that line a try and see if it works as expected in my use
> case and check which tests are failing. Then we can decide if the
> change is "ok".
>
> I agree that I won't recommend removing. Otherwise the service loader
> / security provider detection would have no use at all, right? Still I
> think it is only an indication that something might be needed at
> runtime (but maybe it is not needed at all). That's why I think an
> advice that lets the user know that this in not needed at compile time
> (neither implementation nor api) is useful. Because that is what we
> know for sure.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/autonomousapps/dependency-analysis-android-gradle-
plugin/issues/387#issuecomment-1103510178>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ABJG5PJRSOIFGS5TTX23CJDVF6OFZANCNFSM43Y63ONQ>.
You are receiving this because you were mentioned.Message ID:
<autonomousapps/dependency-analysis-android-gradle-
***@***.***>
