### ISSUE TITLE
"this project has both java-library and org.jetbrains.kotlin.jvm applied" warning should not be printed

### ISSUE THREAD

**Issue by vlsi** [autonomousapps/dependency-analysis-android-gradle-plugin#392]
**Plugin version**

0.73.0

**Gradle version**

6.8.3

**Describe the bug**

I think the advice to remove `java-library` is not justified.

```
  Advice for project :core
  Plugin advice:
  - java-library: this project has both java-library and org.jetbrains.kotlin.jvm applied, which is redundant. You can remove java-library
```

If the plugin detected that the build script used no features from `java-library` plugin (e.g. no custom configurations, etc, then the advice might be great. However, I think it is hard to verify if the script uses no `java-library` features.

In practice, it goes against the line of "declare what you use".
In my build file, I rely on `implementation`, `testImplementation`, and similar features of the `java-library` plugin.
I see no reason why a mere addition of `kotin("jvm")` should case the removal of `java-library`. Of course, `kotlin("jvm")` might apply `java-library` behind the scenes, however, that is implementation detail of `kotlin(jvm)`.

WDYT?

**Comment by autonomousapps** [comment]
Thanks for filing this issue. The initial impetus for the feature was provided by @ZacSweers, although I can't find the issue (he may have suggested it via private communication channels). At the time, it seemed reasonable, but I've always wondered about it a bit.

Zac, I'm pinging you because I'd like your opinion. Do you think that java-library is always redundant when kotlin-jvm is applied?

@vlsi if you have a pure Kotlin project, then I _think_ that most and maybe all cases are handled by applying the kotlin-jvm plugin. I am not 100% sure, however, which is why I think I agree with you on this. I'd like to hear Zac's thoughts, though.

**Comment by vlsi** [comment]
> I think that most and maybe all cases are handled by applying the kotlin-jvm plugin. 

Just in case, the project is https://github.com/apache/calcite

```
98.9% Java
 0.7% Kotlin 
...
```

Kotlin is slowly introduced for test purposes there.

**Comment by ZacSweers** [comment]
What features is `java-library` applying that `kotlin("jvm")` doesn't? Or vice versa?

**Comment by vlsi** [comment]
1) Calcite code is 98.9% Java, and it would be extremely surprising to see kotlin plugin only
2) It would be strange if adding kotlin(jvm) plugin resulted in src/main/java processed by javac
3) The rule of thumb is **declare** used transitive dependencies. Even in case `java-library` is a transitive dependency of kotlin(jvm), that implementation detail might change in the future

**Comment by autonomousapps** [comment]
I've thought about this, and also been bitten by it at work, so I think I want to side with @vlsi here and no longer flag kotlin-jvm + java-library as being problematic. My use-case is a set of convention plugins that are composed together. I have a JavaLibraryConvention that applies java-library, and a KotlinLibraryConvention that applies JavaLibraryConvention because it is functionally a superset of the Java use-case. So those projects are applying both plugins, and I don't think I want to change that setup. Further, while I think that kotlin-jvm is potentially problematic because it's not a core gradle plugin and hasn't always followed best practices, I do _not_ think that java-library generally falls into that category.

So, I think I can imagine calling out kotlin-jvm as redundant if there is no Kotlin code in the project, but I don't think there's much of a use-case for calling out java-library even if there is no Java code.

Thoughts?

**Comment by ZacSweers** [comment]
Seems fine to me

**Comment by autonomousapps** [comment]
This change just landed on `main`.
