### ISSUE TITLE
buildHealth suggests implementation -> testImplementation which causes javac failure since the class is used in src/main/java

### ISSUE THREAD

**Issue by vlsi** [autonomousapps/dependency-analysis-android-gradle-plugin#393]
**Plugin version**
0.73.0

**Gradle version**
6.8.3

**Describe the bug**

The plugin suggests to adjust `implementation` -> `testImplementation` as follows:

```
  Advice for project :core
  Existing dependencies which should be modified to be as indicated:
  - testImplementation("org.apache.commons:commons-dbcp2:2.6.0") (was implementation)
```

however, the advice breaks the build:

```
% ./gradlew -PenableDependencyAnalysis buildHealth

> Configure project :
Building Apache Calcite 1.27.0-SNAPSHOT

> Task :piglet:locateDependenciesMain
Dependency org.checkerframework:checker-qual has been declared multiple times: [api, implementation]

> Task :core:compileJava
/calcite/core/src/main/java/org/apache/calcite/adapter/jdbc/JdbcUtils.java:29: error: package org.apache.commons.dbcp2 does not exist
import org.apache.commons.dbcp2.BasicDataSource;
                               ^
/calcite/core/src/main/java/org/apache/calcite/adapter/jdbc/JdbcUtils.java:258: error: cannot find symbol
    private final LoadingCache<List<@Nullable String>, BasicDataSource> cache =
                                                       ^
  symbol:   class BasicDataSource
  location: class DataSourcePool
/calcite/core/src/main/java/org/apache/calcite/adapter/jdbc/JdbcUtils.java:262: error: cannot find symbol
    private static BasicDataSource dataSource(
                   ^
  symbol:   class BasicDataSource
  location: class DataSourcePool
/calcite/core/src/main/java/org/apache/calcite/adapter/jdbc/JdbcUtils.java:264: error: cannot find symbol
      BasicDataSource dataSource = new BasicDataSource();
      ^
  symbol:   class BasicDataSource
  location: class DataSourcePool
/calcite/core/src/main/java/org/apache/calcite/adapter/jdbc/JdbcUtils.java:264: error: cannot find symbol
      BasicDataSource dataSource = new BasicDataSource();
                                       ^
  symbol:   class BasicDataSource
  location: class DataSourcePool
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
5 errors
```

Here's the class in question: https://github.com/apache/calcite/blob/fc6d56f1ac6d590b8a332cb0931a71ecd2367969/core/src/main/java/org/apache/calcite/adapter/jdbc/JdbcUtils.java#L258-L264

**To Reproduce**

clone https://github.com/apache/calcite
execute `./gradlew -PenableDependencyAnalysis -Pcom.autonomousapps.dependency-analysis.version=0.73.0 buildHealth`

**Expected behavior**

`testImplementation("org.apache.commons:commons-dbcp2")` should be kept as `implementation` since it is needed for `:core` compilation.

**Comment by autonomousapps** [comment]
I have a PR up that will resolve this issue. It turned out to be a pretty bad bug 😅 The plugin was not correctly associating certain constructs with the correct (or any!) source set. In  your case, a static nested class contained the only reference to the class from the `org.apache.commons:commons-dbcp2` dependency in the **main** source set. Furthermore, you had a reference to that dependency in a top-level class in the **test** source set. Because of this, the plugin decided that the dependency should only be on `testImplementation`.

The same issue affected Kotlin source files with multiple top-level declarations.

This bug only made itself visible in cases where the dependency was _only_ used in these cases, which is apparently rare enough that it's taken till now for anyone to notice :)

The resolution was better tracking of source files (and their source sets) to the classes generated by javac/kotlinc.
