### ISSUE TITLE
Detect test dependencies that are mistakenly added to non-test configurations

### ISSUE THREAD

**Issue by yogurtearl** [autonomousapps/dependency-analysis-android-gradle-plugin#434]
**Is your feature request related to a problem? Please describe.**

Sometimes a developer accidentally adds a test dependency to release or production code. 
e.g. 
```kotlin
   // whoops, should have been  testImplementation(project(":test-support:my-test-lib"))
   implementation(project(":test-support:my-test-lib"))

   // whoops, should have been  testImplementation("org.junit:junit:4.13.2")
   implementation("org.junit:junit:4.13.2")
```

This bloats release code and can cause various mysterious issues can be hard to spot... 

**Describe the solution you'd like**

Detect when people write `implementation` when they should have used `testImplementation` instead.

This can be hard to detect automatically... 
because if you are writing a testing lib, then `implementation("org.junit:junit:4.13.2")` is correct! 

But you could look for deps that are included directly in both test and non-test contexts, which might signal there is a problem. 

**Describe alternatives you've considered**

Might need an API to signal if a project is intended to be used as a test dep. 

`my-test-lib/build.gradle.kts` -> 
```
dependencyAnalysis {
     intendedToBeATestDep()
}
```

**Comment by autonomousapps** [comment]
I think the plugin already handles the following case (pseudo-code):
```groovy
// build.gradle
implementation junit4

// src/test/SomeTest.java

public class SomeTest {
  @Test void test() ...
}
```
And because JUnit's `@Test` annotation is only used in a test source set, the plugin will say you can change junit from `implementation` to `testImplementation`.

Are you saying it should go further and flag dependencies that are _only_ meant to be used by tests but are nevertheless on the main compile classpath? I think that would indeed require some kind of new DSL option(s).

**Comment by yogurtearl** [comment]
Same logic works for `project(...)` deps? If so, that probably covers mostly what I was after here. 

The other case is when something should ONLY be used in tests, possible because of license issues, or other reasons. 
And a dev might add it as `implementation` in production code to use one method in there, and it wouldn't get flagged as it is actually being used. But we want to flag it because we intend for that project or dep to only ever be used in test configurations.

**Comment by autonomousapps** [comment]
Can you tell me more about this license-based use-case? I want to
understand it more.

On June 29, 2021, GitHub ***@***.***> wrote:
> Same logic works for project(...) deps? If so, that probably covers
> mostly what I was after here.
>
> The other case is when something should ONLY be used in tests,
> possible because of license issues, or other reasons.
>  And a dev might add it as implementation in production code to use
> one method in there, and it wouldn't get flagged as it is actually
> being used. But we want to flag it because we intend for that project
> or dep to only ever be used in test configurations.
>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/autonomousapps/dependency-analysis-android-gradle-
plugin/issues/434#issuecomment-871072785>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ABJG5PPEWNMU6ZXQVRGC7L3TVKHGJANCNFSM47RGMHEQ>.

**Comment by yogurtearl** [comment]
There may be libraries with licenses that have different restrictions or obligations based how the library is used.

E.g. distribution of the library versus just using at build time. 

So usage in tests may be compliant with the license, but accidentally distributing as part of a production release of software may have different implications under the terms of the license.

(I am not a lawyer or license expert, so take this worth a grain of salt)

**Comment by autonomousapps** [comment]
Thanks, this is an interesting use-case. I don't think it's out of bounds, but I also can't claim that it's something I'll work on in the near future. If it's something _you'd_ like to work on, we could have a conversation about how it might be implemented.

It might also be possible to bolt on this behavior via your own plugin or build script that parses the output of this plugin's tasks.

**Comment by autonomousapps** [comment]
I think you're better off using something like https://github.com/dropbox/dependency-guard for your use-cases.
