### ISSUE TITLE
Gradle intrinsics are reported as null

### ISSUE THREAD

**Issue by ZacSweers** [autonomousapps/dependency-analysis-android-gradle-plugin#464]
**Build scan link**
N/A

**Plugin version**
0.77.0

**Gradle version**
7.2

**(Optional) Android Gradle Plugin (AGP) version**
N/A

**Describe the bug**
In gradle plugin projects, gradle intrinsic deps are shown as null.

```kotlin
plugins {
  `kotlin-dsl`
}

dependencies {
  compileOnly(gradleApi())
}
```

Results in this advice to add

```
  api("Gradle Kotlin DSL:null")
  api("Gradle TestKit:null")
  api("Gradle API:null")
```

**To Reproduce**
See above

**Expected behavior**
Probably not worth mentioning in advice?

**Additional context**

**Comment by autonomousapps** [comment]
Might be something changed in Gradle 7, because I thought this was
handled for 6.

Thanks for the report, will take a look. 

On August 30, 2021, GitHub ***@***.***> wrote:
> Build scan link
>  N/A
>
> Plugin version
>  0.77.0
>
> Gradle version
>  7.2
>
> (Optional) Android Gradle Plugin (AGP) version
>  N/A
>
> Describe the bug
>  In gradle plugin projects, gradle intrinsic deps are shown as null.
>
> plugins { `kotlin-dsl` } dependencies { compileOnly(gradleApi()) }
> Results in this advice to add
>
> api("Gradle Kotlin DSL:null") api("Gradle TestKit:null") api("Gradle
> API:null")
> To Reproduce
>  See above
>
> Expected behavior
>  Probably not worth mentioning in advice?
>
> Additional context
>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/autonomousapps/dependency-analysis-android-gradle-
plugin/issues/464>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ABJG5PNREVAVP5BVTCCEIXDT7QVYVANCNFSM5DDAXH7A>.
Triage notifications on the go with GitHub Mobile for iOS
<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-
email&mt=8&pt=524675> or Android
<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-
email%26utm_medium%3Demail%26utm_source%3Dgithub>.

**Comment by autonomousapps** [comment]
I wonder if you could provide a reproducer? I'm confused why the plugin would tell you to add TestKit as an `api` dep. Also, there's special handling for deps declared as `compileOnly`, so I'm also wondering why that doesn't seem to be working.

Feel free to drop me a line in slack if that's simpler.
