### ISSUE TITLE
All tasks always status "SKIPPED" & empty output

### ISSUE THREAD

**Issue by thahnen** [autonomousapps/dependency-analysis-android-gradle-plugin#478]
**Build scan link**

Sorry not providable, company internal build project.

**Plugin version**

0.78.0

**Gradle version**

7.2

**Describe the bug**

We have a multi-project Java build running on OpenJDK 11 (no Android). Searching for an alternative for Netflix' *nebula.lint plugin* I stumbled upon this plugin. When I applied it to our root project nothing broke but running the Gradle task "buildHealth" as mentioned in this project' README.md at root level brought no result - every task prior to "buildHealth" chose to be "SKIPPED" and the actual task produced some outputs.
These were not completely empty but listed all sub-projects with empty results due to the corresponding tasks being executed and then "SKIPPED" as well.

I tried disabling strict mode but nothing changed. Also running the Gradle task "clean" followed by either "jar" or "testClasses" didn't change anything.

Also running every task at root level and in some sub-projects resulted in all of them being "SKIPPED" or with empty results.

**To Reproduce**

1. Apply plugin
2. Run Gradle task "buildHealth"
3. Try not to cry 😳 

**Expected behavior**

Gradle not skipping every task prior to "buildHealth" and the actual task producing any non-empty output.

**Comment by autonomousapps** [comment]
Try running with --info, as that should indicate why a task is skipped. 

I'll need more information to understand what's going on. What plugins
are you applying? Can you tell me anything about your project
structure? 

On September 16, 2021, GitHub ***@***.***> wrote:
> Build scan link
>
> Sorry not providable, company internal build project.
>
> Plugin version
>
> 0.78.0
>
> Gradle version
>
> 7.2
>
> Describe the bug
>
> We have a multi-project Java build running on OpenJDK 11 (no Android).
> Searching for an alternative for Netflix' nebula.lint plugin I
> stumbled upon this plugin. When I applied it to our root project
> nothing broke but running the Gradle task "buildHealth" as mentioned
> in this project' README.md at root level brought no result - every
> task prior to "buildHealth" chose to be "SKIPPED" and the actual task
> produced some outputs.
>  These were not completely empty but listed all sub-projects with
> empty results due to the corresponding tasks being executed and then
> "SKIPPED" as well.
>
> I tried disabling strict mode but nothing changed. Also running the
> Gradle task "clean" followed by either "jar" or "testClasses" didn't
> change anything.
>
> Also running every task at root level and in some sub-projects
> resulted in all of them being "SKIPPED" or with empty results.
>
> To Reproduce
>
> Steps to reproduce the behavior:
>
> 1. Apply plugin
> 2. Run Gradle task "buildHealth"
> 3. Try not to cry 😳
>
> Expected behavior
>
> Gradle not skipping every task prior to "buildHealth" and the actual
> task producing any non-empty output.
>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/autonomousapps/dependency-analysis-android-gradle-
plugin/issues/478>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ABJG5PJY3FEJYBH5SKNF2ETUCMD2TANCNFSM5EGTTRAQ>.
Triage notifications on the go with GitHub Mobile for iOS
<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-
email&mt=8&pt=524675> or Android
<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-
email%26utm_medium%3Demail%26utm_source%3Dgithub>.

**Comment by autonomousapps** [comment]
@thahnen any update? I'll likely close this issue in the near future if I can't get any more information.
