### ISSUE TITLE
Modify projectHealth task's output to be preformatted for ease of copying

### ISSUE THREAD

**Issue by dkdoo** [autonomousapps/dependency-analysis-android-gradle-plugin#481]
Using the output of the dependency analysis tool is a bit cumbersome at the moment, as output needs to be copied then manually tweaked through a search and replace.

**Describe the solution you'd like**
Rather than printing the missing transitive dependencies as:
```
Transitively used dependencies that should be declared directly as indicated:
- api(project("a:b:c"))
- api(project("aa:bb:cc"))
...
```
It would be nice to have the expected dependencies to be printed to the console so that the entire output can be copy/pasted into our gradle file
ex:
```
Transitively used dependencies that should be declared directly as indicated:
  api project('a:b:c')
  api project('aa:bb:cc')
...
```

**Comment by autonomousapps** [comment]
Thanks for the feature request. This has actually been raised before. I like your idea of dropping the `- ` in favor of just `  `. An IDE would handle the spaces much better than the dash.

Regarding double vs single quotes, the output uses double quotes so that the dependency declarations would work in both Groovy and Kotlin DSL. This is unlikely to change in the near-term, but I can adjust the output for the first point pretty easily.

**Comment by dkdoo** [comment]
Thanks @autonomousapps 

Another change request in the output is to remove the extra pair of parenthesis surrounding the project. wdyt?

api **(** project("a:c:d") **)**

**Comment by autonomousapps** [comment]
Hey @dkdoo that was another decision I made so that the output could be copied and pasted into either a groovy or kotlin script and it would "just work." I understand why you're asking, though, so I'll think about how something like that might best be implemented.

**Comment by autonomousapps** [comment]
The output now does not have `-` in it. Feel free to open a new issue for the groovy vs kotlin DSL request, and thanks.
