### ISSUE TITLE
Make FindAndroidLinters cacheable

### ISSUE THREAD

**Issue by eugene-krivobokov** [autonomousapps/dependency-analysis-android-gradle-plugin#487]
**Is your feature request related to a problem? Please describe.**

`com.autonomousapps.tasks.FindAndroidLinters` task is not cacheable:

![Screenshot from 2021-09-29 12-08-43](https://user-images.githubusercontent.com/1104540/135238924-c331ef5c-f31f-4672-a6b3-3321dd4281e2.png)

They are not heavy but potentially caching may be faster.
I think that this is good to be cacheable by default. Clients can measure and decide on data if it's worth it or not depending on network conditions and overall performance.

**Describe the solution you'd like**

**Describe alternatives you've considered**

--

**Additional context**

Plugin version: 0.78.0
Gradle: 7.2
AGP: 7.0.2

**Comment by autonomousapps** [comment]
This looks like a simple oversight. If you want to contribute a PR, it's a one line fix. At https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/main/src/main/kotlin/com/autonomousapps/tasks/FindAndroidLinters.kt#L21, add the annotation `@CacheableTask`.

**Comment by SubhrajyotiSen** [comment]
@autonomousapps Can I pick this up?

**Comment by autonomousapps** [comment]
Sure! 

On February 23, 2022, GitHub ***@***.***> wrote:
> @autonomousapps <https://github.com/autonomousapps> Can I pick this
> up?
>

—
Reply to this email directly, view it on GitHub
<https://github.com/autonomousapps/dependency-analysis-android-gradle-
plugin/issues/487#issuecomment-1048693889>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ABJG5PL53IQYAGQGGNHI2PTU4TBMLANCNFSM5E7L4TPA>.
Triage notifications on the go with GitHub Mobile for iOS
<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-
email&mt=8&pt=524675> or Android
<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-
email%26utm_medium%3Demail%26utm_source%3Dgithub>.
You are receiving this because you were mentioned.Message ID:
<autonomousapps/dependency-analysis-android-gradle-
***@***.***>
