### ISSUE TITLE
FR - consider androidx ktx libraries to be the same dependency common androidx

### ISSUE THREAD

**Issue by Tapchicoma** [autonomousapps/dependency-analysis-android-gradle-plugin#58]
**Gradle version**
6.1.1

**Android Gradle Plugin (AGP) version**
3.5.5

**Describe the bug**

As we are using kotlin in our project - we define only `-ktx` variants of androidx dependencies, even if code does not use any ktx extensions. Running `adviceDebug` task proposes to replace `-ktx` dependecny with the same dependency but without `-ktx`.

**Expected behavior**
Androidx `-ktx` dependencies are not reported as unused, when only code from non-ktx dependency is used.

**Comment by emartynov** [comment]
I have probably a similar case. @autonomousapps let me know if you want it in a different issue.

We declare a dependency to Android Joda Time but in all modules, except app, we use only Joda Time classes.

Android Joda Time has more efficient initialisation for Android while loading timezones data.

**Comment by autonomousapps** [comment]
I think my resolution to this will be to finish the ignore DSL I'm working
on so you can specify dependencies to ignore. I don't know how I'd
determine a priori that something like android joda time should be OK. I'll
take a look, though.

**Comment by autonomousapps** [comment]
The way I see it, the plugin is _correctly_ reporting that you have an unused direct dependency and a used-transitive dependency. In the absence of any heuristics (such as, if the dependency identifier ends in "-ktx", pretend it doesn't exist), I think the best solution will be to upgrade to v0.19.2 (the latest at time of writing) and use the new ignore-dsl. You would do something like the following:

```groovy
// root build.gradle
dependencyAnalysis {
  issues {
    onAny {
      warn("androidx.core:core-ktx") // takes a vararg String
    }
  }
}
```
Please note that the identifiers should not include version information. You can also use `fail()` instead of `warn()` if you want to fail the build on any issue discovery. Warning is the default behavior.

See the readme for more information.
