### ISSUE TITLE
Printing the report after running buildHealth

### ISSUE THREAD

**Issue by bartek-wesolowski** [autonomousapps/dependency-analysis-android-gradle-plugin#615]
When running `buildHealth`, it would be nice to see the report printed instead of having to open the report file. Right now I just see this:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildHealth'.
> There were dependency violations. See report at /home/github/actions-runner/_work/my-app/my-app/build/reports/dependency-analysis/build-health-report.txt
```
It's particularly painful on CI, where I can't easily open the report file. I have to publish it first in my GitHub workflow, then download the zipped report, uncompress it and open it in a text editor.

**Comment by autonomousapps** [comment]
You can toggle that behavior with `-Pdependency.analysis.print.build.health=true`.

**Comment by bartek-wesolowski** [comment]
Thank you. Perhaps it would be a good idea to add this information to the docs.

**Comment by bartek-wesolowski** [comment]
I run the following command `./gradlew buildHealth -Pdependency.analysis.print.build.health=true` and I still can't see anything printed in the console other than `There were dependency violations. See report at ...`. Is there something I'm doing wrong?

**Comment by autonomousapps** [comment]
I just ran `./gradlew buildHealth -Pdependency.analysis.print.build.health=true` and it worked as expected. Which version of the plugin are you using? Latest is 1.0.0-rc03.

**Comment by bartek-wesolowski** [comment]
I was testing on rc02. On rc03 it works fine. Thanks.
BTW, why isn't `true` the default value? Is there a downside of having the report printed after running `buildHealth`?

**Comment by autonomousapps** [comment]
On large projects, printing that report can take a significant amount of
time and overwhelm the console. It's also unreadable at that length.
However, I might update the code to print instructions on re-enabling
the old behavior to make the flag easier to discover. 

On March 23, 2022, GitHub ***@***.***> wrote:
> I was testing on rc02. On rc03 it works fine. Thanks.
>  BTW, why isn't true the default value? Is there a downside of having
> the report printed after running buildHealth?
>

—
Reply to this email directly, view it on GitHub
<https://github.com/autonomousapps/dependency-analysis-android-gradle-
plugin/issues/615#issuecomment-1076132544>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ABJG5PJVOZ5VNCBZDRFOW23VBLOTZANCNFSM5RKAI6AA>.
You are receiving this because you modified the open/close state.Message
ID: <autonomousapps/dependency-analysis-android-gradle-
***@***.***>
