### ISSUE TITLE
Filtering should support (optional) dependency version

### ISSUE THREAD

**Issue by mvegter** [autonomousapps/dependency-analysis-android-gradle-plugin#639]
**Is your feature request related to a problem? Please describe.**
We maintain a list of dependency declarations which include the version, e.g:
```
gradle/libraries.gradle

ext {
  springVersion = '1.0.0'
  libs.spring = [
    core : "org.springframework:spring-core:${springVersion}",
    expression : "org.springframework:spring-expression:${springVersion}",
  ]
}

subproject/module.gradle

dependencies {
  api libs.spring.core
  implementation libs.spring.expression
}
```

What we would like to do is reuse this declaration in the filtering:
```
dependencyAnalysis {
    issues {
        onUnusedDependencies {
            exclude(
                    libwebapp.spring_expression, // does not work
                    'org.springframework:spring-expression:1.0.0', // does not work
                    'org.springframework:spring-expression', // this works
            )
        }
    }
}
```

**Describe the solution you'd like**
Introduce logic to check first for version ignored, otherwise check if the artifact without version is ignored.

**Comment by autonomousapps** [comment]
Thanks for the request. Sounds reasonable. Is this something you might
be interested in working on? 

On April 17, 2022, GitHub ***@***.***> wrote:
> Is your feature request related to a problem? Please describe.
>  We maintain a list of dependency declarations which include the
> version, e.g:
>
> gradle/libraries.gradle ext { springVersion = '1.0.0' libs.spring = [
> core : "org.springframework:spring-core:${springVersion}", expression
> : "org.springframework:spring-expression:${springVersion}", ] }
> subproject/module.gradle dependencies { api libs.spring.core
> implementation libs.spring.expression }
> What we would like to do is reuse this declaration in the filtering:
>
> dependencyAnalysis { issues { onUnusedDependencies { exclude(
> libwebapp.spring_expression, // does not work
> 'org.springframework:spring-expression:1.0.0', // does not work
> 'org.springframework:spring-expression', // this works ) } } }
> Describe the solution you'd like
>  Introduce logic to check first for version ignored, otherwise check
> if the artifact without version is ignored.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/autonomousapps/dependency-analysis-android-gradle-
plugin/issues/639>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ABJG5PKKU7L2JFVZJIVDCZ3VFPNRZANCNFSM5TTUSXVQ>.
You are receiving this because you are subscribed to this thread.Message
ID: <autonomousapps/dependency-analysis-android-gradle-
***@***.***>
