### ISSUE TITLE
Consider using task.withType<...>() and task.register<...>(...)

### ISSUE THREAD

**Issue by vlsi** [autonomousapps/dependency-analysis-android-gradle-plugin#7]
```kotlin
tasks.withType<PluginUnderTestMetadata>().configureEach {
    pluginClasspath.from(configurations.compileOnly)
}

// and 

tasks.register<DependencyMisuseAggregateReportTask>("misusedDependenciesReport") {
...
```

seem to be easier to follow than `DependencyMisuseAggregateReportTask::class.java`

**Comment by autonomousapps** [comment]
Fixed with https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/commit/bf622536566473f269e896a2ab9a53932d0aaa36.

Please note, `TaskContainer.named()` does not appear to have a generic version, so I couldn't change most of those. The only alternative I can think of is removing the class and using `as SomeClass` instead, but then the IDE warns of unchecked casts.
