### ISSUE TITLE
False-positive with cross-project dependencies

### ISSUE THREAD

**Issue by boris-petrov** [autonomousapps/dependency-analysis-android-gradle-plugin#859]
Thank you for the work on this amazing plugin!

**Plugin version**
1.19.0

**Gradle version**
7.6

**`reason` output for bugs relating to incorrect advice**

**Describe the bug**
I have the following dependency:

```gradle
productionImplementation project(path: ':shared', configuration: 'production')
```

The `dependency-analysis` plugin gives me the following error:

```
Dependencies which should be removed or changed to runtime-only:
  productionRuntimeOnly project(':shared') (was productionImplementation)
```

However, that's not true. I cannot change it to `productionRuntimeOnly` as it won't compile then. I guess the issue is that I'm using the other project with a specific configuration - perhaps that's not implemented correctly in the `dependency-analysis` plugin?

**To Reproduce**
Create a sub-project, create some configuration in it, depend on that from some other project and it should fail.

**Expected behavior**
No error.

**Comment by autonomousapps** [comment]
Thanks for the issue!

**Comment by jjohannes** [comment]
I would say this is not a bug but a non-existing _feature_, which is out of scope of this plugin.

If you refer to arbitrary custom _configurations_ in a dependency declaration, the plugin probably does not know what this conceptually means: Is it a _runtime classpath_, is it a _compile classpath_? The functionality of the plugin relies on being applied in JVM projects where the "Configuration"-Setup follows certain patterns such that things like `api` and `implementation` make sense.

However, I assume that you are doing this in a Java project. It might anyway be better to use [feature variants](https://docs.gradle.org/current/userguide/feature_variants.html) instead of using custom configurations directly. Feature variants will most likely be fully supported by this plugin in the next release (#854).

It's also recommended by Gradle to (at least in JVM projects) to use dependencies with _attributes/capabilities_ instead of directly referring to another configurations by name (https://github.com/gradle/gradle/issues/19615#issuecomment-1016267014). Unfortunately, Gradle doesn't tell you this - I would have voted for deprecation on that issue.
If you use "capabilities" (even without Feature Variants) the plugin should also handle that correctly with #854.

**Comment by autonomousapps** [comment]
With @jjohannes 's comment, I have switched the label to "wontfix" :)

**Comment by boris-petrov** [comment]
Fair enough, thanks for the heads-up and the work on the plugin!
