### ISSUE TITLE
GC overhead limit exceeded

### ISSUE THREAD

**Issue by nailshakurov** [autonomousapps/dependency-analysis-android-gradle-plugin#868]
Run:  ./gradlew buildHealth
What could be the reason for such an error?

![image](https://user-images.githubusercontent.com/11345578/221807684-a2288101-d798-4898-a79c-d4b46576ba36.png)

**Comment by jjohannes** [comment]
This usually means that the Gradle daemon is fighting for memory by running Garbage Collection too often. In larger projects, this plugin usually needs additional memory due to the large amount of data it needs to process. 

You can increase the memory in `gradle.properties` by setting the `-Xmx` JVM argument:

```
org.gradle.jvmargs=-Xmx8g
```

**Comment by autonomousapps** [comment]
Closing as unactionable by the plugin.
