### ISSUE TITLE
Plugin fails with confusing error message when applied only to subproject

### ISSUE THREAD

**Issue by pioterj** [autonomousapps/dependency-analysis-android-gradle-plugin#93]
**Plugin version**
0.32.0

**Gradle version**
6.3

**Android Gradle Plugin (AGP) version**
None - plain Java project

**Describe the bug**

**To Reproduce**
1. Download multi-project sample from https://docs.gradle.org/current/samples/sample_jvm_multi_project_build.html (either Groovy or Kotlin DSL)
2. Add the plugin to one of the subprojects
3. The build fails with `Failed to apply plugin [id 'org.gradle.java-library']`

**Expected behavior**
Either:
- No error message 
- A clear error message indicating what's the issue

**Additional context**
Build scan: https://e.grdev.net/s/pylxzzzrwg5l4/failure?openFailures=WzBd&openStackTraces=WzJd#top=0

**Comment by autonomousapps** [comment]
Can you export that build scan to the public scans server? :) Or provide the stacktrace. I assume the issue here is that the plugin is looking for something in the root (probably at `rootProject.extensions.findByType()!!`), and because it's not there it throws an NPE, or something like that.

The simplest solution for now is to show a helpful error message. But I'm also open to a design discussion if you think it should not be required to apply to the root project.

**Comment by autonomousapps** [comment]
This is now fixed on master (via https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/commit/51526eddfd21aec1c7ae76739dba9efec0b7082e). The commit looks large only because I also ended up dealing with a lot of test-related tech debt at the same time.
