### ISSUE TITLE
Analysis of local projects with mixed Java & Kotlin source sets results in incorrect analysis. Only Kotlin classes get analyzed

### ISSUE THREAD

**Issue by joshfriend** [autonomousapps/dependency-analysis-android-gradle-plugin#948]
**Build scan link**
No public build scans, but noting the IDs of a successful check on macOS (`czhpyt5q5zql4`) and a failing one on linux (`psf4ijexa3ida`)

**Plugin version**
1.21.0

**Gradle version**
8.2.1

**(Optional) Android Gradle Plugin (AGP) version**
8.1.1

**`reason` output for bugs relating to incorrect advice**

On CI, I see several errors, such as this one:
```
Advice for :common:about-screen:impl
Unused dependencies which should be removed:
  implementation project(':common:country:public')
```

and `./gradlew :common:about-screen:impl:reason --id :common:country:public` says

```
* What went wrong:
Execution failed for task ':common:about-screen:impl:reason'.
> A failure occurred while executing com.autonomousapps.tasks.ReasonTask$ExplainDependencyAdviceAction
   > There is no dependency with coordinates ':common:country:public' in this project.
```

And `:common:country:public` is definitely a dependency of all variants in `:common:about-screen:impl`.

**Describe the bug**

CI (linux) is showing different results than macOS builds, and those results are all incorrect like the example above. A comparison of the two build scans shows that both have the same dependencies and build dependencies, but there are differences in task inputs. Unfortunately there's not enough detail in a build scan comparison to show what the actual difference is to know if it's important.

**To Reproduce**
We are trying to reproduce these issues in a sample project which can be shared publicly, but as I'm sure you know this is rather difficult.

**Expected behavior**

CI builds checking for unused dependencies should not have errors that can't be duplicated locally.

**Additional context**

**Comment by autonomousapps** [comment]
This is a collection of at least two (well, three) bugs. The first, the inability to find the requested project for reporting purposes, I have already resolved locally. The second is a kind of shadow of the first and has been longstanding and maybe I'll continue to ignore it for now (it's in `ComputeUsagesTask` and has the result that some analyzed dependencies may not end up in the output of that task if they only have the InferredCapability with a value of false); that "shouldn't happen" but you know. This bug was actually only triggered due to a workaround I implemented [here](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/commit/621ab36deeb12550d3029e531dcdb67c910f6492) for an issue in Gradle (no issue report yet; that's next).

The other bug is a more direct result of the Gradle bug referenced above. The tl;dr is that in a local project with a mixed source set of Java and Kotlin files, Gradle only provides the Kotlin files for analysis; the Java source gets ignored. This results in incorrect dependency analysis. The fix for this is under investigation. I have reported this in a [private slack](https://gradle.slack.com/archives/C01D0BR067J/p1694155979950589?thread_ts=1689884838.088779&cid=C01D0BR067J) (again, public issue pending); noting the link here for my own reference later.

The comment in the private thread is reposted here, again for ease of reference:

> sorry for letting this languish. The problem seems to be worse than I initially realized. Given an `ArtifactCollection`, the result of `configurations[dependencyAnalyzer.compileConfigurationName].artifactsFor(dependencyAnalyzer.attributeValueJar)` (sorry for opaque code, but I hope it more or less makes sense given all this context).
> 
> Further assume that this collection contains artifacts from local projects. Some of these projects have _mixed source sets_ of Java and Kotlin files. E.g., `src/main/java/<package>/Foo.java` and `src/main/java/<package>/Bar.kt`. Please note that this is a _canonical project layout for Android projects_.
> 
> Now, iterate over that collection (each element is a `ResolvedArtifactResult`), calling `it.getFile()` on each. You will end up with a result like `local-project/build/classes/kotlin/main`. *Critically*, the actual class files for this local project are in _both_ of `build/classes/kotlin/main` _and_ `build/classes/java/main`.
> 
> The end result is that if I try to analyze the class files, I'll miss all the Java .class files.

**Comment by autonomousapps** [comment]
Well, as gross as it is, this workaround might be sufficient:
```kotlin
// https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/948#issuecomment-1711177139
val file = if (it.file.path.endsWith("kotlin/main")) {
  it.file.parentFile!!.parentFile!!
} else {
  it.file
}
```

**Comment by autonomousapps** [comment]
The fix here led to https://github.com/autonomousapps/dependency-analysis-gradle-plugin/issues/1811.
